services:
  authservice:
    build: .
    container_name: authservice
    ports:
      - "${SERVER_PORT:-8081}:8081"
    env_file:
      - .env
    environment:
      SPRING_PROFILES_ACTIVE: dev
    restart: unless-stopped
